---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 20m
      receiver: 'default-receiver'

      routes:
      - receiver: 'db-webhook-p1'
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 30m
        match_re:
          severity: critical
          dbtype: "db.*"
      - receiver: 'db-webhook-p2'
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 30m
        match_re:
          severity: warning
          dbtype: "db.*"
      - receiver: 'ciciname-webhook-critical'
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 30m
        match_re:
          team: "ciciname.*"
          severity: critical
      - receiver: 'ciciname-webhook-warning'
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 30m
        match_re:
          team: "ciciname.*"
          severity: warning
      - receiver: 'domain-webhook-warning'
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 24h
        match:
          team: domain-alert
          severity: warning
      - receiver: 'default-receiver'
        group_by: ['alertname']
        match_re:
          alertname: ".*"

    receivers:
    - name: "db-webhook-p1"
      webhook_configs:
      #- url: 'http://aws-webhook-svc/api/aws/feishu/db-webhook-p1/send'
      - url: 'http://aws-webhook-svc/api/aws/feishu/default-receiver/send'
        send_resolved: true
    - name: "db-webhook-p2"
      webhook_configs:
      #- url: 'http://aws-webhook-svc/api/aws/feishu/db-webhook-p2/send'
      - url: 'http://aws-webhook-svc/api/aws/feishu/default-receiver/send'
        send_resolved: true
    - name: "ciciname-webhook-warning"
      webhook_configs:
      #- url: 'http://aws-webhook-svc/api/aws/feishu/rlhy-webhook-warning/send'
      - url: 'http://aws-webhook-svc/api/aws/feishu/default-receiver/send'
        send_resolved: true
    - name: "ciciname-webhook-critical"
      webhook_configs:
      #- url: 'http://aws-webhook-svc/api/aws/feishu/rlhy-webhook-critical/send'
      - url: 'http://aws-webhook-svc/api/aws/feishu/default-receiver/send'
        send_resolved: true
      - send_resolved: false
        url: 'http://aws-webhook-svc/api/aws/oncall'
    - name: "domain-webhook-warning"
      webhook_configs:
      #- url: 'http://aws-webhook-svc/api/aws/feishu/domain-webhook-warning/send'
      - url: 'http://aws-webhook-svc/api/aws/feishu/default-receiver/send'
        send_resolved: true
    - name: "default-receiver"
      webhook_configs:
      - url: 'http://aws-webhook-svc/api/aws/feishu/default-receiver/send'
        send_resolved: false

    inhibit_rules:
      - soucicinamee_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'instance']

    #templates:
    #- /etc/alertmanager/config/*.tmpl

