apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  - name: nginx-80
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: alertmanager

