---
apiVersion: v1
kind: Service
metadata:
  name: mq-name-b
  namespace: infra
spec:
  selector:
    app: mq-nameserver-2
  ports:
    - name: tcp-9876
      port: 9876
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mq-nameserver-2
  namespace: infra
  labels:
    app: mq-nameserver-2
spec:
  serviceName: mq-name-b
  selector:
    matchLabels:
      app: mq-nameserver-2
  template:
    metadata:
      labels:
        app: mq-nameserver-2
        appgroup: mq-nameserver
    spec:
      containers:
      - name: mq-nameserver-2
        image: gehuiwin/rocketmq:4.9.2
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPT_EXT
          value: |-
            -XX:+PerfDisableSharedMem
            -Xloggc:/home/rocketmq/logs/rocketmq_gc.log
            -XX:+PrintGCDetails 
            -XX:+PrintGCDateStamps 
            -XX:+PrintGCTimeStamps
            -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=4 -XX:GCLogFileSize=128M
            -Duser.timezone=Asia/Calcutta -Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn512m
        command:
        - sh
        - mqnamesrv
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 25m
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: logs
          mountPath: /home/rocketmq/logs
      volumes:
      - name: logs
        emptyDir: {}
      # https://kubernetes.io/zh/docs/concepts/scheduling-eviction/assign-pod-node/
#      nodeSelector:
#        type: infra
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  appgroup: mq-nameserver
              namespaces:
              - infra
              topologyKey: kubernetes.io/hostname
            weight: 1
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: appgroup
#                    operator: In
#                    values:
#                      - mq-nameserver
#              topologyKey: kubernetes.io/hostname
  replicas: 1
  updateStrategy:
    type: RollingUpdate
