apiVersion: v1
data:
  sample-pwd-file.json: |-
    {
      "redis://redis6:6379": "",
      "rediss://xxxx.amazonaws.com:6379": "tKZyvtON547IfnhX"
    }
kind: ConfigMap
metadata:
  name: redis-pwd-config
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  #annotations:
  #  prometheus.io/scrape: "true"
  labels:
    app: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - name: tcp-9121
      protocol: TCP
      port: 9121
      targetPort: 9121
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      #annotations:
      #  prometheus.io/path: "/metrics"
      #  prometheus.io/port: "9121"
      #  prometheus.io/scrape: "true"
      labels:
        app: redis-exporter
    spec:
      #nodeSelector:
      #  type: ops-prod-prometheus
      #imagePullSecrets:
      #- name: docker-secret
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.61.0
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_PASSWORD_FILE
          value: /data/sample-pwd-file.json
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 9121
        volumeMounts:
        - mountPath: /data
          name: redis-pwd-file
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: sample-pwd-file.json
            path: sample-pwd-file.json
          name: redis-pwd-config
        name: redis-pwd-file
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/instance: redis-exporter
    app.kubernetes.io/version: "1.61.0"
    app.kubernetes.io/component: exporter
    release: prometheus
spec:
  endpoints:
    - path: /metrics
      port: tcp-9121
      #interval: 15s
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: redis-exporter
