#kubectl create secret docker-registry -h
#kubectl create secret docker-registry pfgc-harbor --docker-username=k8s-pull --docker-password=QpJUfm9LBv --docker-server=https://kubeharbor.cici.com -n ops
---
apiVersion: v1
data:
  .dockerconfigjson: eyJx9fQ==
kind: Secret
metadata:
  name: docker-secret
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
