apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2
  namespace: kube-system
spec:
  #匹配所有节点
  nodeSelector: {}
  #匹配所有 Service
  serviceSelector: {}
  externalIPs: true
  loadBalancerIPs: true
  # 指定网络接口（根据实际情况调整）
  interfaces:
  - "eth0"
  - "enp*"
  - "ens*"
