apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-exporter
  template:
    metadata:
      #annotations:
      #  prometheus.io/path: "/metrics"
      #  prometheus.io/port: "5557"
      #  prometheus.io/scrape: "true"
      labels:
        app: rocketmq-exporter
    spec:
      #nodeSelector:
      #  type: pfgc-ops-prod-prometheus
      #imagePullSecrets:
      #- name: docker-secret
      containers:
      - name: rocketmq-exporter
        image: docker.io/apache/rocketmq-exporter:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5557
          name: http
        command:
        - /bin/sh
        - -c
        - 'java -jar -Xms2g -Xmx2g -Xmn1024m -Xss256k rocketmq-exporter.jar
            --server.port=5557
            --rocketmq.config.namesrvAddr=10.0.11.112:9876
            --rocketmq.config.enableACL=true
            --rocketmq.config.accessKey=RocketMQ
            --rocketmq.config.secretKey=rongliang'
        readinessProbe:
          tcpSocket:
            port: 5557
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 10Mi

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rocketmq-exporter
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: rocketmq-exporter
  podMetricsEndpoints:
  - port: http
